apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: {{ include "demo-3tier-app.namespace" . }}
  labels:
    {{- include "demo-3tier-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.app.service.targetPort }}
          env:
            - name: DB_API_HOST
              value: {{ .Values.app.env.DB_API_HOST | quote }}
            - name: DB_API_PORT
              value: {{ .Values.app.env.DB_API_PORT | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: {{ include "demo-3tier-app.namespace" . }}
  labels:
    {{- include "demo-3tier-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app: demo-app
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
{{- if eq .Values.app.service.type "NodePort" }}
      nodePort: {{ .Values.app.service.nodePort }}
{{- end }}