apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: {{ include "demo-3tier-app.namespace" . }}
  labels:
    {{- include "demo-3tier-app.labels" . | nindent 4 }}
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.mongo.service.targetPort }}
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes:
{{ toYaml .Values.mongo.persistence.accessModes | indent 10 }}
        resources:
          requests:
            storage: {{ .Values.mongo.persistence.size }}