apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web
  namespace: {{ include "demo-3tier-app.namespace" . }}
  labels:
    {{- include "demo-3tier-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: demo-web
  template:
    metadata:
      labels:
        app: demo-web
    spec:
      containers:
        - name: demo-web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.web.service.targetPort }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: web-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: demo-web
  namespace: {{ include "demo-3tier-app.namespace" . }}
  labels:
    {{- include "demo-3tier-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  selector:
    app: demo-web
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}